### PR TITLE
fixes parsing of apostrophes in payees

### LINKED ISSUE #139: Cannot use apostrophe in a transaction payee
When I have

```ledger
2017-02-23 Wendy's
  Expenses:Restaurants    2.76
  amexbce
```

I get this error:

```
Error while parsing /Users/colin/Documents/Finance/Personal/2017/activity.ledger:
[889.17] failure: <eol> expected

2017-02-23 Wendy's

                ^
Input error: Couldn't parse input
```

The obvious workaround is simply to omit the apostrophe, but this is a little bit of a rough edge that has bit me more than once.

### PR DESCRIPTION
**Pull request by gerdreiss**
closes #139

### CODE REVIEW

**Comment by gerdreiss** [comment]
Hi @hrj  this PR fixes the apostrophe in transaction payee, but I'm not sure the fix isn't too general resp. the fix location isn't too central, and doesn't affect something I don't know about. I figured, since we want to let apostrophes be part of parsed values as opposed to StdLexical.token, they can be part of identities. Let me know.

**Comment by hrj** [comment]
@gerdreiss Would it make sense to add the single quote character to `delimiters` instead? Payee is like a comment, it gobbles everything until EOL. So we just have to let the Tokeniser accept it as a token.

(Not tested the idea)

**Comment by hrj** [comment]
@gerdreiss 

I noticed this part only after my previous reply:

> I figured, since we want to let apostrophes be part of parsed values as opposed to StdLexical.token, they can be part of identities. Let me know.

If my previous reply doesn't make sense we can discuss this further. I am not sure what you meant by "as opposed to StdLexical.token"?

**Comment by gerdreiss** [comment]
@hrj What I mean is, StdLexical.token handles the single quote the same way as the double quotes, e.g. as String boundaries/enclosures (not sure how to call them). In AbandonLexer.token this behaviour is overridden (unless I don't really unterstand what I'm talking about ;)). It's not really important though. I'll try to add the single quote to the delimiters and see how it goes.

**Comment by gerdreiss** [comment]
@hrj 
Adding the single quote to the delimiters doesn't seem to work because the parsing result of "Wendy's" becomes "Wendy ' s". When I change

`payee = ((allButEOL)+) ^^ { case x => x.mkString(" ") }`

to 

`payee = ((allButEOL)+) ^^ { case x => x.mkString }`

and use two words for a payee, for example "Wendy's Inn", the result is "Wendy'sInn".

**Comment by hrj** [comment]
@gerdreiss Hmm I wonder whether it will be better to recommend users to just quote the string when it has special characters.

For example, this works, even now:

```
2017/march/3   "wendy's inn"
  bank    400
  cash
```

Otherwise, we will end up with lots of hacks for various characters.

**Comment by gerdreiss** [comment]
@hrj Well, either that, or just allow certain characters for identChar, like single quote, #, etc. We don't have to allow every special character there is...
The solution could be bit more elegant than the one I've committed, namely overriding the identChar definition:

`override def identChar = super.identChar | elem(''')| elem('#')`

instead of adding the single quote to the place where I did:

`identChar ~ rep(identChar | digit | '\'')`

What do you think?

**Comment by hrj** [comment]
I think modifying identifiers is a bad idea. Quoting a string containing special characters is the current recommended solution.

Thanks @gerdreiss for your contribution. I am closing this however.

**Pull request closed without merging**
