### PR TITLE
allow multple comments in a line for the new compact syntax

### PR DESCRIPTION
**Pull request by gerdreiss**
- extended parser for compact transaction syntax to allow multple comments
- added test case for multiple comments in a line

### CODE REVIEW

**Comment by hrj** [comment]
@gerdreiss I think you are on the right track, but this change still affects multi-line-transactions.

Test case:

test143.ledger:
```
2017/march/30
  ; comment 1 ; comment 2
  bank 200
  cash
```

test143.conf
```
inputs += test143.ledger

exports += {
  format = xml
  type = journal
}

reports = []
```

gives:

```
[info]   ; comment 1 ; comment 2
[info]               ^
[info] Input error: Couldn't parse input
```

**Comment by hrj** [comment]
Forgot to mention, I expect it to give the same output as current code. That is:

```
[info] <abandon version="Base: 0.4.0 [2017-03-01 18:39:24.660];CLI: 0.4.0 [2017-03-01 18:39:24.631];">
[info]   <journal>
[info]     <transactions>
[info]       <txn date="2017-03-30">
[info]         <comment> comment 1 ; comment 2</comment>
[info]         <post delta="200" name="bank"></post>
[info]         <post delta="-200" name="cash"></post>
[info]       </txn>
[info]     </transactions>
[info]   </journal>
[info] </abandon>
```

([info] is coming from sbt)

**Comment by gerdreiss** [comment]
Actually, my change does not affect the multiline transactions, because I haven't changed the parsing of those. I understood that we didn't want that from what you've said in your issue comment:

"for now, we will make the syntax change only for single-line-notation. Otherwise it will affect older input files."

I must have misunderstood that. I thought that we want to support multiple comments in one line for compact transaction syntax only. So, do we want to handle the multiple comments there as one? At least that is how I understand the XML output...

**Comment by hrj** [comment]
Regarding your edit: Thanks for looking into it!

**Comment by gerdreiss** [comment]
@hrj Just to avoid further misunderstandings and mistakes ;)

I suppose that this:

```
2017/march/30
  ; comment 1 ; comment 2
  bank 200  ; comment 4 ; comment 3
  cash

```
should lead to this:

```
2017/march/30
  ; comment 1 ; comment 2 ; comment 3
  bank 200  ; comment 4
  cash
```

Correct?

**Comment by hrj** [comment]
Nope :)

Since it's multi-line syntax, it shouldn't change behavior from existing code.

Only single-line syntax (with the dot in the front) needs to change.

Glad you asked! If it's still confusing, we could first try to add tests and then change the code (test driven development).

---

I am nearing my sleep time here. I can look into it tomorrow, if you don't beat me to it.

**Comment by hrj** [comment]
@gerdreiss 

I have added two tests for comments in https://github.com/hrj/abandon/commit/3dc10ea4b81a7945a864a843500b78f2cb5cd3d4

If you rebase this branch and push again, I think this PR will be verified automatically by Travis.

**Comment by hrj** [comment]
@gerdreiss Another tip. If you add "closes #issue-number" to the PR description, the issue will be closed automatically when the PR is merged.

**Comment by gerdreiss** [comment]
@hrj good to know. my next PR will have that description :+1:

**Pull request merged**
